package enablement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String stringData;

   public Address()
   {
   }

   public java.lang.String getStringData()
   {
      return this.stringData;
   }

   public void setStringData(java.lang.String stringData)
   {
      this.stringData = stringData;
   }

   public Address(java.lang.String stringData)
   {
      this.stringData = stringData;
   }

}