package enablement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String firstName;
   private java.lang.String lastName;

   private enablement.Address address;

   public Customer()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public enablement.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(enablement.Address address)
   {
      this.address = address;
   }

   public Customer(java.lang.String firstName, java.lang.String lastName,
         enablement.Address address)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
   }

}